### PR TITLE
reimplement pulsar catalog

### PR DESCRIPTION
**Pull request by nlu90**
As we discussed for redesigning and reimplement the pulsar catalog #446 , this PR is the initial commit. It includes changes:

1. clear catalog options and type name
2. allow to use it access topics already inside a pulsar cluster
3. allow to use it as a general catalog to store generic table information to support cases such as regex pattern topics, accessing data other than pulsar etc.
4. some file reorg and cleanup

-----

Examples of how to use this cagalog:
1. Create the catalog with proper options:
```
create catalog pulsarcatalog
with (
  'type' = 'pulsar-catalog',
  'catalog-admin-url' = 'http://localhost:10080',
  'catalog-service-url' = 'pulsar://localhost:6650',
  'catalog-tenant' = '__flink_catalog',
  'catalog-auth-params' = 'file:///Users/nlu/workspace/projects/apache-pulsar-2.8.0/my-token.txt',
  'catalog-auth-plugin' = 'org.apache.pulsar.client.impl.auth.AuthenticationToken'
);

use catalog pulsarcatalog;
```

2. Use the catalog to query native pulsar topics directly:
```
use `public/default`;
```
```
select * from $TOPIC_IN_PUBLIC_DEFAULT;
```

3. Use the catalog to create generic flink table backed with pulsar topics and query it:
```
CREATE TABLE orders5 (
 `order_id` BIGINT,
 `product_id` BIGINT,
 `total` DOUBLE
) WITH (
  'connector' = 'pulsar',
  'topic-pattern' = 'persistent://public/default/avro-test-insert.*',
  'value.format' = 'avro'
)

select * from orders /*+ OPTIONS('scan.startup.mode'='earliest', 'format'='avro') */;
```

### CODE REVIEW

**Comment by EronWright** [comment]
Could you add some content to the PR description, showing some examples of using the catalog?  Also, please describe how batch vs streaming will work.

**Comment by nlu90** [comment]
@EronWright  I added how to configure the catalog and use it.

Currently the connector is mainly for streaming cases, not sure if it's supporting batch mode.

**Comment by nlu90** [comment]
@syhily @EronWright 

All the unit tests and stylecheck are fixed now. You can take a look when have time.

**Comment by syhily** [comment]
LGTM

**Review by syhily — APPROVED** [review]

**Pull request merged**
