### PR TITLE
add subscriptionName to checkpoint state

### PR DESCRIPTION
**Pull request by jiangqiaodd**
### Motivation
When flink application recovers from checkpoint or savepoint in "EXTERNAL_SUBSCRIPTION MODE",  FlinkPulsarSource does not determine whether the specified subscription name is the same as the one stored in restore State. When changing specified subscription name, it still initial from resotreState.

Compared with kafka, subscription name should be insert into checkpoint state.

### Excepted behavior
When user start application savepoint (or recover from checkpoint), it will
determine whether the restoreState belongs to this subscription name.

### CODE REVIEW

**Comment by jiazhai** [comment]
@jiangqiaodd Thanks for the contribute, Would you please help answer the question from @sijie ?

**Comment by jiangqiaodd** [comment]
> @jiangqiaodd Thanks for the contribute, Would you please help answer the question from @sijie ?

Thanks for the reply, I have resubmitted a new version, which is compatible with the previous restored state

**Comment by jiangqiaodd** [comment]
rerun

**Comment by jiazhai** [comment]
@sijie to help review again

**Pull request merged**
