### PR TITLE
fix flink sql properties key style

### PR DESCRIPTION
**Pull request by jianyun8023**
Since the lowerCamelCase key is changed to low case in the flink sql configuration, this will cause the configuration to be unable to be obtained. Now change the configuration to snake-case, and restore to lowerCamelCase after the task runs.

The document needs to update the format of `pulsar.**` related configuration in sql ddl.

### CODE REVIEW

**Review by syhily — APPROVED** [review]
`CaseFormat` is a interesting util.

**Comment by gaozhangmin** [comment]
this pr will cause another bug， properties like "enable-key-hash-range" would be invalid

**Comment by jianyun8023** [comment]
> this pr will introduce an new bug， properties like "enable-key-hash-range" would be invalid

@gaozhangmin I added a judgment, only deal with the configuration of `pulsar.` prefix, I added compatibility processing for the only affected `failOnDataLoss`.
What do you think?

**Comment by gaozhangmin** [comment]
> pulsar

I agree

> failOnDataLoss

Why `fail-on-data-loss` need special process?

**Comment by jianyun8023** [comment]
> Why `fail-on-data-loss` need special process?

Because its key is `pulsar.reader.fail-on-data-loss`, it takes effect in the connector itself, not in the pulsar client.

**Comment by jianyun8023** [comment]
The reason for adding this processing is that flink SQL converts all upper case keys the `with` block to lower case. Related issue https://issues.apache.org/jira/browse/FLINK-21532

Current time flink version 1.13.0 is fixed. not fixed in version 1.12.

@nlu90

**Comment by nlu90** [comment]
Thanks for the information. 
I think this is a flink issue

**Pull request merged**
