### PR TITLE
Various fixes for build, admin, and multiple schema sink

### PR DESCRIPTION
**Pull request by addisonj**
This commit makes a few primary changes:
- makes a few build fixes, this is primarily so I can build against
scala 2.12 (not in this commit, will see if I can get that in a profile)
- adds auth and TLS support to the admin client, currently, it isn't
authenticated
- tweaks the sink to allow for producing into multiple topics with
different schemas. This isn't supported natively by the higher level Row
and Sink classes, but can now be done by extend in the SinkBase
- some minor formatting changes (done by scalafmt), I didn't realize it
was formatting in this project, but they mostly seem to be improvements,
so figured I would keep it

### CODE REVIEW

**Comment by sijie** [comment]
@yjshen can you please review this pull request?

**Comment by yjshen** [comment]
Hi @addisonj , thanks for your contribution!

Before we start reviewing the PR, could you please revert the style changes made by __scalafmt__?  

I find most of the changes are the style change and we've already enforcing code styles using __scalastyle__.  If there are something style issues, I'd prefer to isolate them into a single PR and add check rules in `tools/maven/scalastyle-config.xml` as well. Any ideas?

Thanks again for your work :)

**Comment by yjshen** [comment]
BTW, please also add license header in each file using: `mvn license:format` and make sure license check and style check passes: `mvn license:check scalastyle:check`

**Comment by sijie** [comment]
@addisonj would you be able to take a look at @yjshen 's comment?

**Comment by addisonj** [comment]
I saw it, haven't had a chance to rip out the formatting scalafmt did.

Will hopefully get a chance to circle back on this later this week. I have
a number of other changes as well that I will try and get cleaned up for
opening up a PR

**Comment by yjshen** [comment]
Hi @addisonj, since the master is back to normal with Pulsar stable version 2.4.2, would you like to rebase this PR? Please revert format change as well, thanks in advance :)

**Comment by yjshen** [comment]
Since we've moved our connector to java implementation, I would close this PR now.

**Pull request closed without merging**
